### ISSUE TITLE
docker部署时，如何将插件中提供的能够在未登录yapi时可以访问的接口添加到yapi的ignoreRouter中?

### ISSUE THREAD

**Issue by dybxin** [fjc0k/docker-YApi#35]
以[yapi-plugin-ww-login](https://www.yuque.com/dongzhikai/el0fkf/fpr4ym)为例:
yapi-plugin-ww-login插件中提供的 '/api/plugin/wx/login' 接口，在回调的时候还未登录yapi,这时候需要在未登录yapi的情况下调用该接口，yapi提供的方法是直接在如下的ignoreRouter数组中加入该接口。 docker 部署时如何将该接口添加到ignoreRouter中？
yapi  /server/controllers/base.js源码 async init(ctx) 方法中:
```
let ignoreRouter = [
      '/api/user/login_by_token',
      '/api/user/login',
      '/api/user/reg',
      '/api/user/status',
      '/api/user/logout',
      '/api/user/avatar',
      '/api/user/login_by_ldap',
      '/api/plugin/wx/login'
    ]
```

**Comment by fjc0k** [comment]
建议克隆本项目自定义镜像。

**Comment by dybxin** [comment]
> 建议克隆本项目自定义镜像。

好的。参考了几款插件，也有直接在插件的controllers方法中采用如下的设置，解决当前的问题。
```
this.$auth = true;
```

**Comment by dybxin** [comment]
> 建议克隆本项目自定义镜像。

构建项目报错:
大概就是些依赖没有拉取下来

**Comment by fjc0k** [comment]
我没用自己电脑构建，国内基本无法正常构建。建议你搞个国外服务器或者用 github actions。

**Comment by dybxin** [comment]
> 我没用自己电脑构建，国内基本无法正常构建。建议你搞个国外服务器或者用 github actions。

好吧，明天翻墙试下。

**Comment by dybxin** [comment]
> 我没用自己电脑构建，国内基本无法正常构建。建议你搞个国外服务器或者用 github actions。

我用香港的服务器编译， 也是报The command '/bin/sh -c yarn build-client' returned a non-zero code: 1:
```
[error] ./~/json-schema-editor-visual/package/components/SchemaComponents/schemaJson.css
Module build failed: ModuleBuildError: Module build failed: Error: ENOENT: no such file or directory, open '/yapi/vendors/node_modules/svgo/lib/svgo/../../.svgo.yml'
    at Object.openSync (fs.js:458:3)
    at Object.readFileSync (fs.js:360:35)
    at module.exports (/yapi/vendors/node_modules/svgo/lib/svgo/config.js:31:48)
    at new module.exports (/yapi/vendors/node_modules/svgo/lib/svgo.js:21:19)
    at /yapi/vendors/node_modules/postcss-svgo/dist/index.js:95:16
    at Object.creator [as postcssSvgo] (/yapi/vendors/node_modules/postcss/lib/postcss.js:150:35)
    at /yapi/vendors/node_modules/cssnano/dist/index.js:295:40
    at Array.forEach (<anonymous>)
    at /yapi/vendors/node_modules/cssnano/dist/index.js:282:29
    at creator (/yapi/vendors/node_modules/postcss/lib/postcss.js:150:35)
    at processCss (/yapi/vendors/node_modules/ykit/node_modules/css-loader/lib/processCss.js:185:16)
    at Object.module.exports (/yapi/vendors/node_modules/ykit/node_modules/css-loader/lib/loader.js:24:2)
    at NormalModule.onModuleBuildFailed (/yapi/vendors/node_modules/webpack-core/lib/NormalModuleMixin.js:315:19)
    at nextLoader (/yapi/vendors/node_modules/webpack-core/lib/NormalModuleMixin.js:270:31)
    at /yapi/vendors/node_modules/webpack-core/lib/NormalModuleMixin.js:292:15
    at runSyncOrAsync (/yapi/vendors/node_modules/webpack-core/lib/NormalModuleMixin.js:173:4)
    at nextLoader (/yapi/vendors/node_modules/webpack-core/lib/NormalModuleMixin.js:290:3)
    at /yapi/vendors/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.provide (/yapi/vendors/node_modules/ykit/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:52:20)
    at CachedInputFileSystem.readFile (/yapi/vendors/node_modules/ykit/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:140:24)
    at NormalModule.onLoadPitchDone (/yapi/vendors/node_modules/webpack-core/lib/NormalModuleMixin.js:255:7)
    at NormalModule.loadPitch (/yapi/vendors/node_modules/webpack-core/lib/NormalModuleMixin.js:182:27)
    at NormalModule.loadPitch (/yapi/vendors/node_modules/webpack-core/lib/NormalModuleMixin.js:186:21)
    at NormalModule.loadPitch (/yapi/vendors/node_modules/webpack-core/lib/NormalModuleMixin.js:223:61)
    at NormalModule.doBuild (/yapi/vendors/node_modules/webpack-core/lib/NormalModuleMixin.js:241:4)
    at NormalModule.build (/yapi/vendors/node_modules/ykit/node_modules/webpack/lib/NormalModule.js:84:14)
    at Compilation.buildModule (/yapi/vendors/node_modules/ykit/node_modules/webpack/lib/Compilation.js:126:9)
    at Compilation.<anonymous> (/yapi/vendors/node_modules/ykit/node_modules/webpack/lib/Compilation.js:398:8)

[error] ./client/containers/Project/Interface/InterfaceList/editor.css
Module build failed: ModuleBuildError: Module build failed: Error: ENOENT: no such file or directory, open '/yapi/vendors/node_modules/svgo/lib/svgo/../../.svgo.yml'
    at Object.openSync (fs.js:458:3)
    at Object.readFileSync (fs.js:360:35)
    at module.exports (/yapi/vendors/node_modules/svgo/lib/svgo/config.js:31:48)
    at new module.exports (/yapi/vendors/node_modules/svgo/lib/svgo.js:21:19)
    at /yapi/vendors/node_modules/postcss-svgo/dist/index.js:95:16
    at Object.creator [as postcssSvgo] (/yapi/vendors/node_modules/postcss/lib/postcss.js:150:35)
    at /yapi/vendors/node_modules/cssnano/dist/index.js:295:40
    at Array.forEach (<anonymous>)
    at /yapi/vendors/node_modules/cssnano/dist/index.js:282:29
    at creator (/yapi/vendors/node_modules/postcss/lib/postcss.js:150:35)
    at processCss (/yapi/vendors/node_modules/ykit/node_modules/css-loader/lib/processCss.js:185:16)
    at Object.module.exports (/yapi/vendors/node_modules/ykit/node_modules/css-loader/lib/loader.js:24:2)
    at NormalModule.onModuleBuildFailed (/yapi/vendors/node_modules/webpack-core/lib/NormalModuleMixin.js:315:19)
    at nextLoader (/yapi/vendors/node_modules/webpack-core/lib/NormalModuleMixin.js:270:31)
    at /yapi/vendors/node_modules/webpack-core/lib/NormalModuleMixin.js:292:15
    at runSyncOrAsync (/yapi/vendors/node_modules/webpack-core/lib/NormalModuleMixin.js:173:4)
    at nextLoader (/yapi/vendors/node_modules/webpack-core/lib/NormalModuleMixin.js:290:3)
    at /yapi/vendors/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.provide (/yapi/vendors/node_modules/ykit/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:52:20)
    at CachedInputFileSystem.readFile (/yapi/vendors/node_modules/ykit/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:140:24)
    at NormalModule.onLoadPitchDone (/yapi/vendors/node_modules/webpack-core/lib/NormalModuleMixin.js:255:7)
    at NormalModule.loadPitch (/yapi/vendors/node_modules/webpack-core/lib/NormalModuleMixin.js:182:27)
    at NormalModule.loadPitch (/yapi/vendors/node_modules/webpack-core/lib/NormalModuleMixin.js:186:21)
    at NormalModule.loadPitch (/yapi/vendors/node_modules/webpack-core/lib/NormalModuleMixin.js:223:61)
    at NormalModule.doBuild (/yapi/vendors/node_modules/webpack-core/lib/NormalModuleMixin.js:241:4)
    at NormalModule.build (/yapi/vendors/node_modules/ykit/node_modules/webpack/lib/NormalModule.js:84:14)
    at Compilation.buildModule (/yapi/vendors/node_modules/ykit/node_modules/webpack/lib/Compilation.js:126:9)
    at Compilation.<anonymous> (/yapi/vendors/node_modules/ykit/node_modules/webpack/lib/Compilation.js:398:8)

[error] ./client/styles/theme.less
Module build failed: ModuleBuildError: Module build failed: Error: ENOENT: no such file or directory, open '/yapi/vendors/node_modules/svgo/lib/svgo/../../.svgo.yml'
    at Object.openSync (fs.js:458:3)
    at Object.readFileSync (fs.js:360:35)
    at module.exports (/yapi/vendors/node_modules/svgo/lib/svgo/config.js:31:48)
    at new module.exports (/yapi/vendors/node_modules/svgo/lib/svgo.js:21:19)
    at /yapi/vendors/node_modules/postcss-svgo/dist/index.js:95:16
    at Object.creator [as postcssSvgo] (/yapi/vendors/node_modules/postcss/lib/postcss.js:150:35)
    at /yapi/vendors/node_modules/cssnano/dist/index.js:295:40
    at Array.forEach (<anonymous>)
    at /yapi/vendors/node_modules/cssnano/dist/index.js:282:29
    at creator (/yapi/vendors/node_modules/postcss/lib/postcss.js:150:35)
    at processCss (/yapi/vendors/node_modules/css-loader/lib/processCss.js:199:16)
    at Object.module.exports (/yapi/vendors/node_modules/css-loader/lib/loader.js:40:2)
    at NormalModule.onModuleBuildFailed (/yapi/vendors/node_modules/webpack-core/lib/NormalModuleMixin.js:315:19)
    at nextLoader (/yapi/vendors/node_modules/webpack-core/lib/NormalModuleMixin.js:270:31)
    at /yapi/vendors/node_modules/webpack-core/lib/NormalModuleMixin.js:292:15
    at runSyncOrAsync (/yapi/vendors/node_modules/webpack-core/lib/NormalModuleMixin.js:173:4)
    at nextLoader (/yapi/vendors/node_modules/webpack-core/lib/NormalModuleMixin.js:290:3)
    at /yapi/vendors/node_modules/webpack-core/lib/NormalModuleMixin.js:292:15
    at context.callback (/yapi/vendors/node_modules/webpack-core/lib/NormalModuleMixin.js:148:14)
    at /yapi/vendors/node_modules/less-loader/dist/processResult.js:34:5
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
The command '/bin/sh -c yarn build-client' returned a non-zero code: 1
[root@iZj6cc4w2ham1fp939fxllZ docker-YApi]# 

```

**Comment by dybxin** [comment]
> 我没用自己电脑构建，国内基本无法正常构建。建议你搞个国外服务器或者用 github actions。

还有一点请教下，我本地打包镜像直接 docker build -t xxxxx:latest . 就行吧 ，
关于package.josn 和 Dockerfile.web中的需要改吗？ 对于这块不太熟。

**Comment by dybxin** [comment]
目前在执行clean.ts 如下代码时，会有错误：
```
Step 12/20 : RUN node /yapi/scripts/clean.js $(pwd)
 ---> Running in 1a84199382f6
(node:1) UnhandledPromiseRejectionWarning: Error: EXDEV: cross-device link not permitted, rename '/yapi/vendors/node_modules/ajv-i18n/localize/es' -> '/yapi/vendors/node_modules/ajv-i18n/localize/r_es'
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by dybxin** [comment]
> 目前在执行clean.ts 如下代码时，会有错误：
> 
> ```
> Step 12/20 : RUN node /yapi/scripts/clean.js $(pwd)
>  ---> Running in 1a84199382f6
> (node:1) UnhandledPromiseRejectionWarning: Error: EXDEV: cross-device link not permitted, rename '/yapi/vendors/node_modules/ajv-i18n/localize/es' -> '/yapi/vendors/node_modules/ajv-i18n/localize/r_es'
> (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
> (node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> ```

https://github.com/docker/hub-feedback/issues/852

**Comment by dybxin** [comment]
> 目前在执行clean.ts 如下代码时，会有错误：
> 
> ```
> Step 12/20 : RUN node /yapi/scripts/clean.js $(pwd)
>  ---> Running in 1a84199382f6
> (node:1) UnhandledPromiseRejectionWarning: Error: EXDEV: cross-device link not permitted, rename '/yapi/vendors/node_modules/ajv-i18n/localize/es' -> '/yapi/vendors/node_modules/ajv-i18n/localize/r_es'
> (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
> (node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> ```

这里的错误您这边有遇到过吗？

**Comment by dybxin** [comment]
> 我没用自己电脑构建，国内基本无法正常构建。建议你搞个国外服务器或者用 github actions。

 换了三台服务器都没有编译成功 @fjc0k

**Comment by fjc0k** [comment]
自行构建镜像遇到的问题自行解决。我没那时间处理。

**Comment by dybxin** [comment]
> 自行构建镜像遇到的问题自行解决。我没那时间处理。

上面的问题已经解决 现在的问题是 YAPI_PLUGINS 加入插件后 重新编译就会出现源码中/exts/yapi-plugin-wiki的错误： 
```
[error] ./exts/yapi-plugin-wiki/wikiPage/Editor.js
yapi-web      | Module not found: Error: Cannot resolve 'file' or 'directory' ../../../common/tui-editor/dist/tui-editor-Editor-all.min.js in /yapi/vendors/exts/yapi-plugin-wiki/wikiPage
yapi-web      |  @ ./exts/yapi-plugin-wiki/wikiPage/Editor.js 35:29-100
yapi-web      | 
yapi-web      | 
yapi-web      | [error] ./exts/yapi-plugin-wiki/wikiPage/Editor.js
yapi-web      | Module not found: Error: Cannot resolve 'file' or 'directory' ../../../common/tui-editor/dist/tui-editor.min.css in /yapi/vendors/exts/yapi-plugin-wiki/wikiPage
yapi-web      |  @ ./exts/yapi-plugin-wiki/wikiPage/Editor.js 41:0-61
yapi-web      | 
yapi-web      | [error] ./exts/yapi-plugin-wiki/wikiPage/Editor.js
yapi-web      | Module not found: Error: Cannot resolve 'file' or 'directory' ../../../common/tui-editor/dist/tui-editor-contents.min.css in /yapi/vendors/exts/yapi-plugin-wiki/wikiPage
yapi-web      |  @ ./exts/yapi-plugin-wiki/wikiPage/Editor.js 42:0-70

```

**Comment by fjc0k** [comment]
更新镜像

**Comment by dybxin** [comment]
> 更新镜像

好的
