### ISSUE TITLE
K8S部署yapi，通过环境变量替换YAPI_PLUGINS报错

### ISSUE THREAD

**Issue by areswxin** [fjc0k/docker-YApi#50]
K8S部署yapi，通过环境变量替换YAPI_PLUGINS报错
覆盖其他配置没有问题，YAPI_PLUGINS报错

配置： YAPI_PLUGINS: [{"name":"gitlab","options":{}}]

报错如下：
undefined:1
[map[name:gitlab options:map[]]]
 ^

SyntaxError: Unexpected token m in JSON at position 1
    at JSON.parse (<anonymous>)
    at Function.extractConfigFromEnv (/yapi/vendors/start.js:175:40)
    at Function.extractConfig (/yapi/vendors/start.js:213:44)
    at new Main (/yapi/vendors/start.js:295:36)
    at Object.<anonymous> (/yapi/vendors/start.js:370:1)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)

求大佬看下

**Comment by fjc0k** [comment]
你试试把 json 用单引号括起来：`YAPI_PLUGINS: '[{"name":"gitlab","options":{}}]'`
