### ISSUE TITLE
docker build 报错

### ISSUE THREAD

**Issue by LittleSecretary** [fjc0k/docker-YApi#65]
![image](https://user-images.githubusercontent.com/24629157/103002309-a3fbc180-4569-11eb-8053-5c8c6150eaa0.png)
打包镜像报错

**Comment by LittleSecretary** [comment]
[error] ./~/react/index.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./cjs/react.production.min.js in E:\yapi2\vendors\node_modules\react        
 @ ./~/react/index.js 4:19-59

[error] ./~/react-dom/index.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./cjs/react-dom.production.min.js in E:\yapi2\vendors\node_modules\react-dom
 @ ./~/react-dom/index.js 35:19-63

[error] ./~/history/index.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./cjs/history.min.js in E:\yapi2\vendors\node_modules\history
 @ ./~/history/index.js 4:19-50

[error] ./client/styles/common.scss
Module build failed: Error: ENOENT: no such file or directory, open 'E:\yapi2\vendors\node_modules\svgo\lib\svgo/../../.svgo.yml'
    at Object.openSync (fs.js:440:3)
    at Object.readFileSync (fs.js:342:35)
    at module.exports (E:\yapi2\vendors\node_modules\svgo\lib\svgo\config.js:31:48)
    at new module.exports (E:\yapi2\vendors\node_modules\svgo\lib\svgo.js:21:19)
    at E:\yapi2\vendors\node_modules\postcss-svgo\dist\index.js:95:16
    at Object.creator [as postcssSvgo] (E:\yapi2\vendors\node_modules\postcss\lib\postcss.js:150:35)
    at E:\yapi2\vendors\node_modules\cssnano\dist\index.js:295:40
    at Array.forEach (<anonymous>)
    at E:\yapi2\vendors\node_modules\cssnano\dist\index.js:282:29
    at creator (E:\yapi2\vendors\node_modules\postcss\lib\postcss.js:150:35)
    at processCss (E:\yapi2\vendors\node_modules\css-loader\lib\processCss.js:199:16)
    at Object.module.exports (E:\yapi2\vendors\node_modules\css-loader\lib\loader.js:40:2)
 @ ./client/index.js 7:0-31

[error] ./~/react-is/index.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./cjs/react-is.production.min.js in E:\yapi2\vendors\node_modules\react-is
 @ ./~/react-is/index.js 4:19-62

**Comment by blackkeai** [comment]
我也是跟你一样，也报错了。
