### ISSUE TITLE
想添加插件，怎么都不能添加

### ISSUE THREAD

**Issue by lucky-xin** [fjc0k/docker-YApi#67]
yarn run v1.22.4

$ NODE_ENV=production ykit pack -m

[error] ./~/swagger-client/lib/http.js
Module parse failed: /yapi/vendors/node_modules/swagger-client/lib/http.js Unexpected token (41:6)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (41:6)
    at Parser.pp$4.raise (/yapi/vendors/node_modules/ykit/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/yapi/vendors/node_modules/ykit/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp.semicolon (/yapi/vendors/node_modules/ykit/node_modules/acorn/dist/acorn.js:581:61)
    at Parser.pp$1.parseExpressionStatement (/yapi/vendors/node_modules/ykit/node_modules/acorn/dist/acorn.js:966:10)
    at Parser.pp$1.parseStatement (/yapi/vendors/node_modules/ykit/node_modules/acorn/dist/acorn.js:730:24)
    at Parser.pp$1.parseTopLevel (/yapi/vendors/node_modules/ykit/node_modules/acorn/dist/acorn.js:638:25)
    at Parser.parse (/yapi/vendors/node_modules/ykit/node_modules/acorn/dist/acorn.js:516:17)
    at Object.parse (/yapi/vendors/node_modules/ykit/node_modules/acorn/dist/acorn.js:3098:39)
    at Parser.parse (/yapi/vendors/node_modules/ykit/node_modules/webpack/lib/Parser.js:902:15)
    at NormalModule.<anonymous> (/yapi/vendors/node_modules/ykit/node_modules/webpack/lib/NormalModule.js:104:16)
    at NormalModule.onModuleBuild (/yapi/vendors/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
    at nextLoader (/yapi/vendors/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
    at /yapi/vendors/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.finished (/yapi/vendors/node_modules/ykit/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at /yapi/vendors/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
 @ ./~/swagger-client/lib/index.js 12:36-53

[error] ./~/swagger-client/lib/resolver.js
Module parse failed: /yapi/vendors/node_modules/swagger-client/lib/resolver.js Unexpected token (123:38)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (123:38)
    at Parser.pp$4.raise (/yapi/vendors/node_modules/ykit/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/yapi/vendors/node_modules/ykit/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp.expect (/yapi/vendors/node_modules/ykit/node_modules/acorn/dist/acorn.js:597:28)
    at Parser.pp$3.parseMaybeConditional (/yapi/vendors/node_modules/ykit/node_modules/acorn/dist/acorn.js:1626:12)
    at Parser.pp$3.parseMaybeAssign (/yapi/vendors/node_modules/ykit/node_modules/acorn/dist/acorn.js:1597:21)
    at Parser.pp$3.parseExprList (/yapi/vendors/node_modules/ykit/node_modules/acorn/dist/acorn.js:2165:22)
    at Parser.pp$3.parseSubscripts (/yapi/vendors/node_modules/ykit/node_modules/acorn/dist/acorn.js:1741:35)
    at Parser.pp$3.parseExprSubscripts (/yapi/vendors/node_modules/ykit/node_modules/acorn/dist/acorn.js:1718:17)
    at Parser.pp$3.parseMaybeUnary (/yapi/vendors/node_modules/ykit/node_modules/acorn/dist/acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (/yapi/vendors/node_modules/ykit/node_modules/acorn/dist/acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (/yapi/vendors/node_modules/ykit/node_modules/acorn/dist/acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (/yapi/vendors/node_modules/ykit/node_modules/acorn/dist/acorn.js:1597:21)
    at Parser.pp$3.parseExpression (/yapi/vendors/node_modules/ykit/node_modules/acorn/dist/acorn.js:1573:21)
    at Parser.pp$1.parseReturnStatement (/yapi/vendors/node_modules/ykit/node_modules/acorn/dist/acorn.js:839:33)
    at Parser.pp$1.parseStatement (/yapi/vendors/node_modules/ykit/node_modules/acorn/dist/acorn.js:699:34)
    at Parser.pp$1.parseBlock (/yapi/vendors/node_modules/ykit/node_modules/acorn/dist/acorn.js:981:25)
 @ ./~/swagger-client/lib/index.js 14:40-61

[error] ./~/swagger-client/lib/subtree-resolver/index.js
Module parse failed: /yapi/vendors/node_modules/swagger-client/lib/subtree-resolver/index.js Unexpected token (20:6)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (20:6)
    at Parser.pp$4.raise (/yapi/vendors/node_modules/ykit/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/yapi/vendors/node_modules/ykit/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp.semicolon (/yapi/vendors/node_modules/ykit/node_modules/acorn/dist/acorn.js:581:61)
    at Parser.pp$1.parseExpressionStatement (/yapi/vendors/node_modules/ykit/node_modules/acorn/dist/acorn.js:966:10)
    at Parser.pp$1.parseStatement (/yapi/vendors/node_modules/ykit/node_modules/acorn/dist/acorn.js:730:24)
    at Parser.pp$1.parseTopLevel (/yapi/vendors/node_modules/ykit/node_modules/acorn/dist/acorn.js:638:25)
    at Parser.parse (/yapi/vendors/node_modules/ykit/node_modules/acorn/dist/acorn.js:516:17)
    at Object.parse (/yapi/vendors/node_modules/ykit/node_modules/acorn/dist/acorn.js:3098:39)
    at Parser.parse (/yapi/vendors/node_modules/ykit/node_modules/webpack/lib/Parser.js:902:15)
    at NormalModule.<anonymous> (/yapi/vendors/node_modules/ykit/node_modules/webpack/lib/NormalModule.js:104:16)
    at NormalModule.onModuleBuild (/yapi/vendors/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
    at nextLoader (/yapi/vendors/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
    at /yapi/vendors/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.finished (/yapi/vendors/node_modules/ykit/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at /yapi/vendors/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
 @ ./~/swagger-client/lib/index.js 16:46-75

[error] ./~/swagger-client/~/buffer/index.js
Module parse failed: /yapi/vendors/node_modules/swagger-client/node_modules/buffer/index.js Unexpected token (1216:24)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (1216:24)
    at Parser.pp$4.raise (/yapi/vendors/node_modules/ykit/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/yapi/vendors/node_modules/ykit/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp$3.parseExprAtom (/yapi/vendors/node_modules/ykit/node_modules/acorn/dist/acorn.js:1822:12)
    at Parser.pp$3.parseExprSubscripts (/yapi/vendors/node_modules/ykit/node_modules/acorn/dist/acorn.js:1715:21)
    at Parser.pp$3.parseMaybeUnary (/yapi/vendors/node_modules/ykit/node_modules/acorn/dist/acorn.js:1692:19)
    at Parser.pp$3.parseExprOp (/yapi/vendors/node_modules/ykit/node_modules/acorn/dist/acorn.js:1656:43)
    at Parser.pp$3.parseExprOp (/yapi/vendors/node_modules/ykit/node_modules/acorn/dist/acorn.js:1658:21)
    at Parser.pp$3.parseExprOp (/yapi/vendors/node_modules/ykit/node_modules/acorn/dist/acorn.js:1656:26)
    at Parser.pp$3.parseExprOps (/yapi/vendors/node_modules/ykit/node_modules/acorn/dist/acorn.js:1639:17)
    at Parser.pp$3.parseMaybeConditional (/yapi/vendors/node_modules/ykit/node_modules/acorn/dist/acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (/yapi/vendors/node_modules/ykit/node_modules/acorn/dist/acorn.js:1597:21)
    at Parser.pp$1.parseVar (/yapi/vendors/node_modules/ykit/node_modules/acorn/dist/acorn.js:1034:28)
    at Parser.pp$1.parseVarStatement (/yapi/vendors/node_modules/ykit/node_modules/acorn/dist/acorn.js:917:10)
    at Parser.pp$1.parseStatement (/yapi/vendors/node_modules/ykit/node_modules/acorn/dist/acorn.js:706:19)
    at Parser.pp$1.parseBlock (/yapi/vendors/node_modules/ykit/node_modules/acorn/dist/acorn.js:981:25)
    at Parser.pp$3.parseFunctionBody (/yapi/vendors/node_modules/ykit/node_modules/acorn/dist/acorn.js:2105:24)
 @ ./~/swagger-client/lib/execute/oas3/style-serializer.js 9:4-21

[error] index@4167bd46eab811188811.js from UglifyJs
SyntaxError: Name expected [../~/swagger-client/lib/commonjs.js:3,0]

error Command failed with exit code 1.

info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by lucky-xin** [comment]
环境变量.env配置如下
YAPI_ADMIN_ACCOUNT=xxx
YAPI_ADMIN_PASSWORD=xxx
YAPI_CLOSE_REGISTER=false
YAPI_NPM_REGISTRY=https://registry.npm.taobao.org

YAPI_DB_SERVERNAME=xxx
YAPI_DB_PORT=xx
YAPI_DB_DATABASE=xxx
YAPI_DB_USER=xxx
YAPI_DB_PASS=xxx
YAPI_DB_AUTH_SOURCE=xx

YAPI_MAIL_ENABLE=false
YAPI_LDAP_LOGIN_ENABLE=false
YAPI_PLUGINS=[{ "name": "interface-oauth2-token","options":{} }, { "name": "export-docx-data","options":{} }]

docker-compose.yml 内容如下
version: '3.8'

services:
  yapi-web:
    image: jayfong/yapi:latest
    container_name: yapi-web
    ports:
      - 40001:3000
    env_file:
      - .env
    volumes:
      - ./my-yapi:/my-yapi
    restart: unless-stopped

**Comment by lucky-xin** [comment]
![image](https://user-images.githubusercontent.com/13815910/103737301-e4a90f80-502c-11eb-83b1-713fabc15ec5.png)
内存使用信息

**Comment by Xmlssun** [comment]
同样问题，而且 docker-compose restart 还是会读取旧得配置信息，

**Comment by feg545** [comment]
官方的ykit.config.js脚本配置有问题, 可以参考https://github.com/YMFE/yapi/issues/2109 进行解决
